### ISSUE TITLE
Would be good to add corpus based evaluation

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#2]
The well-known problem in ATR is the lack of evaluation protocol and standards to compare performances of a proliferation of algorithms. It would be good to add corpus based evaluation taking annotated corpus as input and output benchmark result with selected algorithms. It should naively support some well-known gold standards : 

* [GENIA corpus] (http://www.nactem.ac.uk/meta-knowledge/download.php)
* [The Colorado Richly Annotated Full Text Corpus (CRAFT)](http://bionlp-corpora.sourceforge.net/CRAFT/)
* [ACL Reference Dataset for Terminology Extraction and Classification (ACL RD-TEC)] (http://acl-arc.comp.nus.edu.sg/)
* etc.

**Comment by ziqizhang** [comment]
TBD as publication

**Comment by ziqizhang** [comment]
test cases added based on two datasets. results reported in paper
