### ISSUE TITLE
Large scaled term extraction

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#3]
There is a performance issue for computational expensive term extraction (e.g., contigency table based Chi Square test, mutual information, Z-score) when dealing with a large corpus.

It would be good to add:
1) parallel processing configurable with multi-core processor resource;
2) mapReduce model support for cloud/cluster computing;
3) association rule algorithms (e.g., Apriori, FP-Growth)
4) PMI algorithm

**Comment by ziqizhang** [comment]
the code has been improved largely and now it should be faster. Memory is still the bottleneck as on large dataset coocurrence matrix will be huge. However this can not be dealt with easily. This is to be solved in the next release, possibility involves using Spark.
