### ISSUE TITLE
Cannot build with sbt since Dragon tool not linked

### ISSUE THREAD

**Issue by hschildt** [ziqizhang/jate#31]
Related to the Troubleshooting part in wiki, the artifact edu.drexel:dragontool:jar:1.3.3 is creating a problem with SBT: 
[warn] 	:: edu.drexel#dragontool;1.3.3: not found
I have dragontool.jar in my lib folder, but it seems to want find .../drexel/dragontool/1.3.3/dragontool-1.3.3.pom file.
I am quite new to SBT and maven so if this is a trivial and ignorant issue then please forgive me.
Kindly, 
Henri

**Comment by jerrygaoLondon** [comment]
Sorry for late response to this issue. This is actually mentioned in [Quick Start](https://github.com/ziqizhang/jate/wiki/Quick-start).  You can either manually configure it in your IDE, or run mvn install to install it in your local maven repository properly. 

You can follow the examples in maven documentation, access via https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
