### ISSUE TITLE
term candidate extraction issue

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#4]
@ziqizhang We can support three types of candidates extraction. This is optional as user can configure solr.TermRecognitionRequestHandler to rank and filter only on pre-processed term field.

*  Part-of-Speech sequence/pattern
*  Ngram based
*  Noun-Phrase (NP) chunking

The settings vary from different methods. 

###  Part-of-Speech sequence/pattern filter

*   part-of-speech(pos) sequence pattern for filtering term candidate lexical units
pos_sequence_filter=../config/pos_sequence_filter3

*   Maximum number of characters (single candidate term unit) is useful to overcome the erroneous PoS tagging or irregular text in order to increase precision
max_char_length=10

*   Minimum number of characters allowed in any term candidates units. increase for better precision
min_char_length=1

* Stopwords filtering is quite domain-specific and useful to increase precision. This can be default to use SMART stop-word list built by Chris Buckley
stopwords=stoplist.txt

*  Minimum frequency allowed for term candidates.; increase for better precision. This is a corpus level statistic based filtering, we can leave to term extraction request handler
min_term_freq=2

### Ngram filter

Ngram based term candidate generation is useful in the situation where linguistic and language resource/tool is lack. In solr, we can generate ngrams by means of sol.ShingleFilterFactory. Ngram based filter should be more aggressive in order to balance precision and recall for different domains.

*   Maximum number of words allowed in a multi-word term. Adjust the range to balance precision and recall.

max_tokens=5
*  Minimum number of words allowed in a multi-word term. Adjust the range to balance precision and recall.

min_tokens=1

* Stopwords filtering is useful here to increase precision
stopwords=stoplist.txt

*   Maximum number of characters (single candidate term unit) is useful to increase precision. This is to increase precision in irregular text
max_char_length=10

*   Minimum number of characters allowed in any term candidates units. increase for better precision
min_char_length=1

*  Minimum frequency allowed for term candidates.; increase for better precision. This is a corpus level statistic based filtering, we can leave to term extraction request handler
min_term_freq=2

### Noun-Phrase (NP) chunking

Noun-phrase (NP) chunking has some advantage by using machine learning model trained on domain-specific corpus.

*   Maximum number of words allowed in a multi-word term. Adjust the range to balance precision and recall. 

max_tokens=5

*  Minimum number of words allowed in a multi-word term. Adjust the range to balance precision and recall.

min_tokens=1

*   Maximum number of characters (single candidate term unit) is useful to increase precision. This is to increase precision in irregular text
max_char_length=10

*   Minimum number of characters allowed in any term candidates units. increase for better precision
min_char_length=1

*  Minimum frequency allowed for term candidates.; increase for better precision. This is a corpus level statistic based filtering, we can leave to term extraction request handler
min_term_freq=2

### Stopwords filtering strategy

Two different strategy for stopwords filtering we can implement:

*   Aggressive approach: remove whole term candidates if there is any stopword detected

Aggressive approach based stopword filtering is useful for ngram based term candidate extraction method, since all the possible combinations of term candidates are generated in extraction stage.

*   Conservative approach: remove only the term unit (heuristic rule: for only first N terms in compound term) if it is matched with a stopword

The conservative approach is beneficial for PoS pattern based approach in order to increase recall.

Suggested modification for current setting:

we can modify uk.ac.shef.dcs.jate.lucene.filter.OpenNLPRegexChunkerFactory first to support a stopword filter to only filter substring stopwords from candidates (with options for ignoreCase, etc)

An example of filter configuration would be:

```
<filter class="uk.ac.shef.dcs.jate.lucene.filter.OpenNLPRegexChunkerFactory"
							posTaggerClass="uk.ac.shef.dcs.jate.nlp.opennlp.POSTaggerOpenNLP"
							posTaggerModel="D:/Work/jate_github/jate/resource/en-pos-maxent.bin"
							patterns="D:/Work/jate_github/jate/jate.candidate.patterns"
stopwords="stopwords.txt"
ignoreCase="false"/>`
```

**Comment by ziqizhang** [comment]
Done.

Now Jate supports 2 open filters: n-gram, POS pattern; and 1 closed filter: NP chunking
