### ISSUE TITLE
Upgrade JATE to use latest Solr?

### ISSUE THREAD

**Issue by MysterionRise** [ziqizhang/jate#40]
What do you think about it?

I mean, I could do this by myself, just want to get confirmation

**Comment by jerrygaoLondon** [comment]
Thanks for your interest. That will be our next plan, but i can't confirm you with a specific time. What is your use case ? which mode are you interested to try with?  If plugin mode will be used, you can install JATE2 as a plugin in latest Solr, it should work fine for most of algorithms. We are aware of some minor issues with latest Solr version and will fix them later.

**Comment by MysterionRise** [comment]
I'm using it as a plugin. It's clearly have some issues. I could create a
pull request with the fixes I did, that add support for latest Sol the
version, so you could spend your time on other problems, WDYT?

On Jul 20, 2017 00:12, "jerrygao" <notifications@github.com> wrote:

Thanks for your interest. That will be our next plan, but i can't confirm
you with a specific time. What is your use case ? which mode are you
interested to try with? If plugin mode will be used, you can install JATE2
as a plugin in latest Solr, it should work fine for most of algorithms. We
are aware of some minor issues with latest Solr version and will fix them
later.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ziqizhang/jate/issues/40#issuecomment-316518988>, or mute
the thread

**Comment by jerrygaoLondon** [comment]
That will be very appreciated if you can create a pull request for your fixes. We will test and fix various issues in latest version later.

**Comment by MysterionRise** [comment]
Will work on it
