### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: org.apache.solr.common.SolrInputDocument.<init>([Ljava/lang/String;)

### ISSUE THREAD

**Issue by MoonTreee** [ziqizhang/jate#44]
Thanks 4 your wonderful work ,but I got a issue with  Solr when uploading my docs.

**Comment by ziqizhang** [comment]
Hi

It seems the program cannot find your java classes. Can you double check you have used the right jar, and also the right flag with your java command?

Can you be more specific with what you are trying to do, and what command/procedure you have used?

**Comment by ziqizhang** [comment]
I am closing this issue as there is no reply from the OP. Feel free to re-open it if you still need help on this.
