### ISSUE TITLE
Porting to ESearch? 

### ISSUE THREAD

**Issue by cbobed** [ziqizhang/jate#52]
Hi all, 

first of all, congrats for such a good project. I've come across JATE as I'm taking a look on automatic term extraction literature to test a disambiguation approach I'm working on. Unfortunately, my ecosystem is currently built on top of Elasticsearch. Do you think it'd be worthy considering porting JATE 2.0 to ESearch? I'm going to use it as a separate module, but I wanted to ask this just in case the interaction with Solr was isolated in a connector and the port could be feasible (At first sight, I'm assuming that at least it would require the implementation effort of porting the analyzers to ESearch, as well as the appropriate connectors and candidate ranking algorithms). 

Thank you very much,

**Comment by jerrygaoLondon** [comment]
Many thanks for your interests. Porting JATE to Elasticsearch is a good suggestion, however, it requires non-trivial work. We do not have short-term plan and funding to support this further work. Although the proposed conceptual architecture can be applied to any content indexing engine, current JATE2.0 implementations and key components (inc. pre-processing, candidate extraction and ranking algorithms) rely so much on Lucene and Solr Ecosystem.

**Comment by cbobed** [comment]
Thank you for your answer. It's then what I thought :)
Anyway, taking a further look at JATE 2.0, it seems that using it as a separate module is exactly what I need. I'll keep in touch to give you further info about the problem and the results obtained (if I get any :) ) 

Best,
